[package]
name = "blain/ballmatter"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
matter = "evaera/matter@0.6.2"
Comm = "sleitnick/comm@0.3.1"
